name: zeropoint
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.4.4 <4.0.0'

# Dependências que sua aplicação precisa para funcionar
dependencies:
  flutter:
    sdk: flutter

  # Pacote de localização oficial do Flutter
  flutter_localizations:
    sdk: flutter

  # Pacotes que a aplicação precisa para rodar
  cupertino_icons: ^1.0.6
  provider: ^6.0.2
  path_provider: ^2.1.1
  http: ^1.4.0
  shared_preferences: ^2.5.3
  file_saver: ^0.3.1
  crypto: ^3.0.3
  fl_chart: ^0.68.0
  intl: ^0.20.2       # <-- VERSÃO ATUALIZADA PARA RESOLVER O CONFLITO
  firebase_auth: ^5.1.2
  firebase_core: ^3.14.0

# Dependências apenas para desenvolvimento (testes, etc.)
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - images/